all:
	mkdir autoload
	curl -LSso autoload/pathogen.vim https://tpo.pe/pathogen.vim
	mkdir bundle
	cd bundle && git clone git@github.com:skywind3000/asyncrun.vim
	cd bundle && git clone git@github.com:Rip-Rip/clang_complete
	cd bundle && git clone git@github.com:altercation/vim-colors-solarized
